{% set name = "emoji" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e048dd540a0644bd30790b540466492f1487a3788528422fe196a939a7a3ac0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7

test:
  imports:
    - emoji

about:
  home: https://github.com/carpedm20/emoji/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Emoji for Python

  dev_url: https://github.com/carpedm20/emoji/

extra:
  recipe-maintainers:
    - synapticarbors
