{% set name = "emoji" %}
{% set version = "2.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8c50043d79a2c1410ebfae833ae1868d5941a67a6cd4d18377e2eb0bd79346b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=65.0.0
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.7.0

test:
  imports:
    - emoji
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/carpedm20/emoji/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Emoji for Python

  dev_url: https://github.com/carpedm20/emoji/

extra:
  recipe-maintainers:
    - synapticarbors
